# Overview
# This workflow will pull latest Docker image from our repo,
# build a new image with the discord bot token, and deploy it the remote server.

# Required Secrets:
# Docker Account
# -  DOCKERHUB_USERNAME 
# -  DOCKERHUB_TOKEN
# Remote Server Info
# -  REMOTE_SERVER
# -  REMOTE_SERVER_SSH_KEY
# Discord Bot Token
# -  DISCORD_TOKEN

name: Docker CD

on:
  push:
    branches:
      - "main"

env:
  USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
  REMOTE_SERVER: ${{ secrets.REMOTE_SERVER }}
  SSH_KEY: ${{ secrets.REMOTE_SERVER_SSH_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.USERNAME }}
          password: ${{ env.TOKEN }}
      -
        name: Connecting to SSH remote server
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/pph.key
          chmod 600 ~/.ssh/pph.key
          cat >>~/.ssh/config <<END
          Host pph
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/pph.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ env.SERVER_USERNAME }}
          SSH_KEY: ${{ env.SSH_KEY }}
          SSH_HOST: ${{ env.REMOTE_SERVER }}
      -
        name: Restarting Docker container and building latest image
        run: |
          ssh pph 'docker stop progphil-bot'
